# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='master.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmaster.proto\"7\n\x0bJoinRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0e\n\x06weight\x18\x03 \x01(\x05\"(\n\tJoinReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x1a\n\x0cLeaveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1d\n\nLeaveReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x90\x01\n\x0cStateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tcpu_usage\x18\x02 \x01(\x02\x12\x0f\n\x07task_id\x18\x03 \x01(\x05\x12\x0f\n\x07io_perf\x18\x04 \x01(\x02\x12\x10\n\x08pro_perf\x18\x05 \x01(\x02\x12\x0f\n\x07task_st\x18\x06 \x01(\x05\x12\x0f\n\x07task_ed\x18\x07 \x01(\x05\x12\x0b\n\x03utx\x18\x08 \x01(\x03\"\x0b\n\tSateReply\"C\n\x0cRouteRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x0f\n\x07task_sz\x18\x02 \x01(\x05\x12\x11\n\ttask_type\x18\x03 \x01(\x05\":\n\nRouteReply\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x12\n\nthread_num\x18\x03 \x01(\x05\"Q\n\nResultInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\x12\x11\n\ttime_cost\x18\x03 \x01(\x05\x12\x13\n\x0bperformance\x18\x04 \x01(\x05\x32\xd5\x01\n\x06Master\x12\"\n\x04Join\x12\x0c.JoinRequest\x1a\n.JoinReply\"\x00\x12%\n\x05Leave\x12\r.LeaveRequest\x1a\x0b.LeaveReply\"\x00\x12(\n\tPushState\x12\r.StateRequest\x1a\n.SateReply\"\x00\x12*\n\nRouteGuide\x12\r.RouteRequest\x1a\x0b.RouteReply\"\x00\x12*\n\x0cSubmitResult\x12\x0b.ResultInfo\x1a\x0b.ResultInfo\"\x00\x62\x06proto3'
)




_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='JoinRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='JoinRequest.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='JoinRequest.weight', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=71,
)


_JOINREPLY = _descriptor.Descriptor(
  name='JoinReply',
  full_name='JoinReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='JoinReply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='JoinReply.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=113,
)


_LEAVEREQUEST = _descriptor.Descriptor(
  name='LeaveRequest',
  full_name='LeaveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LeaveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=141,
)


_LEAVEREPLY = _descriptor.Descriptor(
  name='LeaveReply',
  full_name='LeaveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='LeaveReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=172,
)


_STATEREQUEST = _descriptor.Descriptor(
  name='StateRequest',
  full_name='StateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StateRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpu_usage', full_name='StateRequest.cpu_usage', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='StateRequest.task_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='io_perf', full_name='StateRequest.io_perf', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pro_perf', full_name='StateRequest.pro_perf', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_st', full_name='StateRequest.task_st', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_ed', full_name='StateRequest.task_ed', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utx', full_name='StateRequest.utx', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=319,
)


_SATEREPLY = _descriptor.Descriptor(
  name='SateReply',
  full_name='SateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=332,
)


_ROUTEREQUEST = _descriptor.Descriptor(
  name='RouteRequest',
  full_name='RouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='RouteRequest.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_sz', full_name='RouteRequest.task_sz', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_type', full_name='RouteRequest.task_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=401,
)


_ROUTEREPLY = _descriptor.Descriptor(
  name='RouteReply',
  full_name='RouteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='RouteReply.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='RouteReply.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thread_num', full_name='RouteReply.thread_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=461,
)


_RESULTINFO = _descriptor.Descriptor(
  name='ResultInfo',
  full_name='ResultInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ResultInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ResultInfo.task_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_cost', full_name='ResultInfo.time_cost', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='performance', full_name='ResultInfo.performance', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=544,
)

DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinReply'] = _JOINREPLY
DESCRIPTOR.message_types_by_name['LeaveRequest'] = _LEAVEREQUEST
DESCRIPTOR.message_types_by_name['LeaveReply'] = _LEAVEREPLY
DESCRIPTOR.message_types_by_name['StateRequest'] = _STATEREQUEST
DESCRIPTOR.message_types_by_name['SateReply'] = _SATEREPLY
DESCRIPTOR.message_types_by_name['RouteRequest'] = _ROUTEREQUEST
DESCRIPTOR.message_types_by_name['RouteReply'] = _ROUTEREPLY
DESCRIPTOR.message_types_by_name['ResultInfo'] = _RESULTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUEST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:JoinRequest)
  })
_sym_db.RegisterMessage(JoinRequest)

JoinReply = _reflection.GeneratedProtocolMessageType('JoinReply', (_message.Message,), {
  'DESCRIPTOR' : _JOINREPLY,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:JoinReply)
  })
_sym_db.RegisterMessage(JoinReply)

LeaveRequest = _reflection.GeneratedProtocolMessageType('LeaveRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEAVEREQUEST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:LeaveRequest)
  })
_sym_db.RegisterMessage(LeaveRequest)

LeaveReply = _reflection.GeneratedProtocolMessageType('LeaveReply', (_message.Message,), {
  'DESCRIPTOR' : _LEAVEREPLY,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:LeaveReply)
  })
_sym_db.RegisterMessage(LeaveReply)

StateRequest = _reflection.GeneratedProtocolMessageType('StateRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEREQUEST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:StateRequest)
  })
_sym_db.RegisterMessage(StateRequest)

SateReply = _reflection.GeneratedProtocolMessageType('SateReply', (_message.Message,), {
  'DESCRIPTOR' : _SATEREPLY,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:SateReply)
  })
_sym_db.RegisterMessage(SateReply)

RouteRequest = _reflection.GeneratedProtocolMessageType('RouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREQUEST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:RouteRequest)
  })
_sym_db.RegisterMessage(RouteRequest)

RouteReply = _reflection.GeneratedProtocolMessageType('RouteReply', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREPLY,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:RouteReply)
  })
_sym_db.RegisterMessage(RouteReply)

ResultInfo = _reflection.GeneratedProtocolMessageType('ResultInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESULTINFO,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:ResultInfo)
  })
_sym_db.RegisterMessage(ResultInfo)



_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='Master',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=547,
  serialized_end=760,
  methods=[
  _descriptor.MethodDescriptor(
    name='Join',
    full_name='Master.Join',
    index=0,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Leave',
    full_name='Master.Leave',
    index=1,
    containing_service=None,
    input_type=_LEAVEREQUEST,
    output_type=_LEAVEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PushState',
    full_name='Master.PushState',
    index=2,
    containing_service=None,
    input_type=_STATEREQUEST,
    output_type=_SATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RouteGuide',
    full_name='Master.RouteGuide',
    index=3,
    containing_service=None,
    input_type=_ROUTEREQUEST,
    output_type=_ROUTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitResult',
    full_name='Master.SubmitResult',
    index=4,
    containing_service=None,
    input_type=_RESULTINFO,
    output_type=_RESULTINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER

# @@protoc_insertion_point(module_scope)
